### PR TITLE
chore: enhance CI tests

### PR DESCRIPTION
**Pull request by KrzysztofMoch**
## Summary
- Added linters and code formatters for native code (Swift, Kotlin, Clang). 
- Updated/Added workflows to check those linters on **PRs** and **pushs** to `master`
- Add sample build to test native changes

## Test plan
All "native" actions should fail for now, as we didn't lint & format code yet

## Parts
- [x] native linters
- [x] JS/TS check #3394
- [x] android/iOS build #3365

### CODE REVIEW

**Comment by freeboub** [comment]
@KrzysztofMoch can you create a PR with only job:
Check JS / Check TS (tsc) 
This one can be merged immediatlly !
Thanks

**Comment by freeboub** [comment]
you can also merge with master as there are conflicts with my changes.
There is one PR with adError and after we will be able to pass linter !
Thanks

**Comment by KrzysztofMoch** [comment]
Okay will do it

**Comment by KrzysztofMoch** [comment]
@freeboub as #3381 is merged, can we go with this one ?

**Comment by freeboub** [comment]
Yes GO !

**Comment by KrzysztofMoch** [comment]
Now we need to lint code to pass test 😄

**Comment by freeboub** [comment]
> Now we need to lint code to pass test 😄

I was thinking you will do it before merging it 😱

**Comment by KrzysztofMoch** [comment]
Ops will do separate PR 😅

**Pull request merged**
